### ISSUE TITLE
Alpha state always displayed in training bar

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#110]
We need the alpha status to always be displayed in training bar.

Either check the option to show expiration time by default or add a bypass for alpha characters
Second options is preferred

Said option : 
![image](https://cloud.githubusercontent.com/assets/10325988/20787202/f0d7589e-b7aa-11e6-95c0-500ff7f0c161.png)

**Comment by Slivo-fr** [comment]
Done using alpha status exception. Need testing !

**Comment by dukrat** [comment]
Looks good.

**Comment by Slivo-fr** [comment]
Thanks for testing, closing the issue
