### ISSUE TITLE
HQF - Estimated training time

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#112]
In some cases (maybe always), HQF only sum the top level skill training requirement instead of adding every sub requirement. The Estimated queue time is wrong.

![image](https://cloud.githubusercontent.com/assets/10325988/20798085/ec54fcf8-b7dd-11e6-810d-4566eb78e1bf.png)

### Objective ###
Rework calculation to make total correct.

**Comment by PaulKPetersonCO** [comment]
I cannot get this to break

**Comment by Slivo-fr** [comment]
I'll try to provide a way to reproduce this issue

**Comment by Slivo-fr** [comment]
Founds it, was two différents bugs.

First, we did not calculate prerequisites of already injected skills because how it works before.
Finally, we didn't calculate the training of a prerequisite if we were already training the last level of this said prerequisite.

I'm glad I had the problem on my own, I don't know how a user could make me reproduce this.

**Comment by Slivo-fr** [comment]
Should be fixed with c5cc650825fe63d7cebd0845fec3449f64ecc8b3
Testing needed (It might cause some side effects)

**Comment by dukrat** [comment]
Seems to work.

**Comment by Slivo-fr** [comment]
Thanks ! Closing :)
