### ISSUE TITLE
HQF damage analysis crash

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#125]
The damange analysis seems to crash in some context. See http://evehq.co/forum/viewtopic.php?f=5&t=377

### Objective ###
Fix the issue, at least avoid the crash

**Comment by PaulKPetersonCO** [comment]
Working this.

It appears that the attribute "1354" "aoeDamageReductionSensitivity" is no longer used.

**Comment by PaulKPetersonCO** [comment]
Thread with missile damage formula
https://oldforums.eveonline.com/?a=topic&threadID=901280&page=3

Will use 5.5 instead based on quite a few pages like this
https://wiki.agony-unleashed.com/index.php/Missle_Damage

**Comment by Slivo-fr** [comment]
Thanks ! Testing needed :)

**Comment by dukrat** [comment]
Looks good.  

Not sure if it was always like this (in which case a new bug is needed) or not but velocity doesn't seem to go into the calculation.  For example my hound was hitting a apoc going 10km/s for full damage which I don't believe it will apply any damage at that speed.

**Comment by Slivo-fr** [comment]
The explosion velocity might need to be added later yeah
Thanks for testing
