### ISSUE TITLE
Change ID from int to long

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#131]
CCP is changing the var type of severals ID. See https://developers.eveonline.com/blog/article/character-id-range-change

We need to change our var type to get along with this.

**Comment by Slivo-fr** [comment]
Done, need testing !

**Comment by dukrat** [comment]
Looks fine.  All the API pulls I could find still work.

**Comment by PaulKPetersonCO** [comment]
Looks good to me too

**Comment by Slivo-fr** [comment]
Thanks, closing :)
