### ISSUE TITLE
One page manufacturing profit margins

### ISSUE THREAD

**Issue by demortes** [Slivo-fr/EveHQ#35]
I'd like to see on EVE Prism where you might list all your blueprints you own and their potential profits based on EVE Central market prices.

**Comment by Slivo-fr** [comment]
Hi Demortes, thanks for suggestings your ideas/needs.

However, you should prefer joining us on the official forum at evehq.co over the github ticket that isn't used. 
As you may know, we are currently working on a C# port of EveHQ and probably won't do big changes to the actual version.
