### ISSUE TITLE
Find a way to increase version number automatically

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#5]
Mercurial was managing version number of evehq, we need to do something similar

**Comment by MHacker9404** [comment]
Short term solution – linked file with the assemblyversion attribute that we manually update.

**Comment by Slivo-fr** [comment]
Yup, that's what I did to get the update system functioning.
The last part of the version number is still a problem, I guess it mached with the number of build in the previous system, and I won't count my builds manually x)

**Comment by MHacker9404** [comment]
Neither do I

**Comment by Slivo-fr** [comment]
It sound like there is some solution, I just gave it a quick look and didn't get the time to try yet.
I'll try http://nowfromhome.com/msbuild-add-git-commit-hash-to-assemblyinfo/ on my holyday comeback
