### ISSUE TITLE
New mining drones

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#74]
New mining drones (including an ‘Excavator’ Mining Superdrone and the first ever ice mining drones) have been added, new mining drone skills have been introduced.
-> Need to check their effects in CSV files

**Comment by Slivo-fr** [comment]
Working on this

**Comment by Slivo-fr** [comment]
Everything seems fine, can someone take a second look ?

**Comment by dukrat** [comment]
Looks fine except the icon is missing for Ice Harvesting Drone I

**Comment by Slivo-fr** [comment]
I saw yeah, it's not on our side, CCP didn't make the icon available yet, it will fix itself.
