### ISSUE TITLE
Mining skills

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#76]
Mining Drone Specialization, Ice Harvester Drone Operation, Ice Harvester Drone Specialization
-> Add effect of those new skills

**Comment by Slivo-fr** [comment]
I'm working on this

**Comment by Slivo-fr** [comment]
Done, need testing :)

**Comment by dukrat** [comment]
Mining Drone II is not affected by Mining Drone Specialization.  

Not sure if the mining amount on ice harvesting drones should be increased like it is by drone interfacing.

Required skills for mining drone I/II and ice harvesting drone I are not correct.  

Otherwise looks good.

**Comment by Slivo-fr** [comment]
I had to change the cache creator a bit to make prerequite skill works, are you sure you rebuilt it before testing ?

**Comment by dukrat** [comment]
Aye.  Harvester Civilian appear to be similarly affected.  But the others are fine.

**Comment by Slivo-fr** [comment]
Well, Mining drone II does not require Mining Drone Specialization, that's why :D
There is an issue on drone skill requirement on the other hand, you are right.

Drone interfacing seems to affect ice mining drone in game

**Comment by Slivo-fr** [comment]
My refactor was a bit too agressive, I fixed it in 3cc2ecc3709e07dfef4551efcd3dbb00e7c37edb
Can someone review it again as I changed a bit of code ?

**Comment by dukrat** [comment]
Drone skill requirements look good now.  I spot checked a few modules as well and they seemed fine.

**Comment by Slivo-fr** [comment]
Thanks, closing :D
