### ISSUE TITLE
Command processor

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#78]
The Command Processor I mid-slot module will be converted to a Medium Command Processor I rig
-> Check effect and update if needed

**Comment by PaulKPetersonCO** [comment]
Working this

**Comment by Slivo-fr** [comment]
Done, need testing

**Comment by dukrat** [comment]
Looks good.

**Comment by Slivo-fr** [comment]
Thanks for testing :)
