### ISSUE TITLE
Command burst charges

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#79]
Note that the Command Bursts modules require Command Burst Charges in order to operate. These charges were introduced in the previous release in order to allow supplies to be built in advance.
-> Check if charges need to have an effect added

**Comment by Slivo-fr** [comment]
See #73

**Comment by PaulKPetersonCO** [comment]
Working this

**Comment by PaulKPetersonCO** [comment]
FYI

This works a little different and I could not find anything in the YAML and SDE for this.

Charges all have 1-4 warfareBuffx ID and multiplier, the burst module has a value that relates to and effects these. Charges with 1 effect definition only use Buff1, those with 2 use Buff2. It looks like the phenomena use all 4.

I am still using the resources below to see how to break these into effects. Each charge can have multiple bonuses, each bonus appears to have a unique ID and value(multiplier) and can have lots of effects.

Pyfa discussions reference this link for json file with definitions. Not sure where he got it.
https://gist.github.com/blitzmann/027e50b0356675e0c5db1aece8f0d186

**Comment by Slivo-fr** [comment]
Damnit, doesn't sounds trivial :/

**Comment by Slivo-fr** [comment]
Can you confirm your last PR resolve this issue ?

**Comment by Slivo-fr** [comment]
Every bonuses are fine, good job !
However, the local buff must be related to the module state (online, active)
Last point, the multiplier of the command burst does not affect the charge bonus on the ship as it should (and so ship bonus that affect module multiplier are not calculated too)

**Comment by dukrat** [comment]
I'm also pretty sure when you do it this way, even after you add in the module effects on the charges you're going to have the base ship effecting the bonus instead of (or possibly in addition to) the remote ship.  So it won't be possible to see the effects of Titan bursts on a Carrier for example.

**Comment by Slivo-fr** [comment]
I'm going to test this dukrat, I don't see why it would have this behavior

**Comment by Slivo-fr** [comment]
Just did some testing, module state are fine and multiplier works !

However, it look like the calculation are wrong at some point : I tried to compare a wyvern with a T2 shield command burst (with caldari carrier skill leve > 0) to a drake with a T2 shield command burst in remote effects.
The remoting drake effect is giving more shield than the local (and theoretically, buffed by skill) command burst. Some singularity or pyfa comparison could help us to see where we are wrong.

**Comment by dukrat** [comment]
Needs testing after merge.  Would be best to retest it all again but should only need to be tested on one ship pair.

**Comment by Slivo-fr** [comment]
I will test this asap :)

**Comment by Slivo-fr** [comment]
Tested, seems better, can't compare the values ingame as I cannot use command bursts
