### ISSUE TITLE
Roqual changes

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#80]
Roqual changes
-> Update rorqual and industrial core effects

**Comment by Slivo-fr** [comment]
Working on this

**Comment by Slivo-fr** [comment]
Done, need testing !

**Comment by dukrat** [comment]
None of the Industrial Core effects seem to be working.  

Rorq bonuses look good.

**Comment by Slivo-fr** [comment]
Industrial core is another issue, not done yet. 
Thanks for testing!
