### ISSUE TITLE
Phenomena Generators

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#82]
Phenomena Generators have been introduced
-> Check if we need some effects too

**Comment by PaulKPetersonCO** [comment]
See #79 for extra info

**Comment by Slivo-fr** [comment]
How is it related to #79 ?

**Comment by Slivo-fr** [comment]
Can you confirm your last PR resolve this issue ?

**Comment by PaulKPetersonCO** [comment]
I will check on the Phenomena Generators. I do not think I added all of the effects for those, just the burst charges. They should be very similar though.

**Comment by Slivo-fr** [comment]
done with #113, need testing !

**Comment by dukrat** [comment]
I don't think they are considered remote effects at the moment.

**Comment by Slivo-fr** [comment]
Just tested it effects are good, however the module does not affect the local ship.
Please add local effects on the fitted titan :D

**Comment by PaulKPetersonCO** [comment]
Added ModuleStates.Active to the status field

**Comment by Slivo-fr** [comment]
Local buff and module states are fine, thanks for your help !
