### ISSUE TITLE
Porpoise 

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#83]
The Porpoise is a new ship Industrial Command Ship
-> We need to add ship effects to CSV

**Comment by PaulKPetersonCO** [comment]
I will work on this one.

**Comment by Slivo-fr** [comment]
Done, need some testing !

(See #90)

**Comment by dukrat** [comment]
Drone ice harvesting cycle time has wrong sign, it should be negative.  Not sure if the mining amount on ice harvesting drones should be increased like it is.  

Otherwise looks good.

**Comment by Slivo-fr** [comment]
Indeed, I missread the bonuses for harvesting drone mining amount !
Fixed with 815745a04527b328d80697c11c00ca0f0c2432d8

Thanks for your help
