### ISSUE TITLE
Orca changes

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#84]
The Orca is receiving a massive overhaul
-> update effects

**Comment by PaulKPetersonCO** [comment]
I will try this one next.

**Comment by Slivo-fr** [comment]
Done, need testing !

**Comment by dukrat** [comment]
Role mining yield should be 100 not 50.  

Drone ice harvesting cycle time has wrong sign, it should be negative. Not sure if the mining amount on ice harvesting drones should be increased like it is.

Otherwise looks good.

**Comment by Slivo-fr** [comment]
I'm fixing this !

**Comment by Slivo-fr** [comment]
Fixed in 0f2adaf59608a8f16f9c075f2d3d4906c41adde2
