### ISSUE TITLE
Sunesis

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#86]
The new Sunesis destroyer has been introduced
-> add effects

**Comment by Slivo-fr** [comment]
I'll work on this

**Comment by Slivo-fr** [comment]
Done, need testing

**Comment by dukrat** [comment]
Missing the light missile and rocket damage bonus.

**Comment by Slivo-fr** [comment]
what a noob ... Fix incoming

**Comment by Slivo-fr** [comment]
Fixed in 70c972fd5cad15ffbd6d6b0222fcfc67e86e0d10
