### ISSUE TITLE
skill Invulnerability Core Operation

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#87]
Added new skill Invulnerability Core Operation
-> See if it need an effect

**Comment by Slivo-fr** [comment]
I'm working on this

**Comment by Slivo-fr** [comment]
Done, need testing

**Comment by dukrat** [comment]
Tested.  Skill affects cycle time and effect duration as desired.

**Comment by Slivo-fr** [comment]
Thanks, closing
