### ISSUE TITLE
skill Spatial Phenomena Generation

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#88]
Added new skill Spatial Phenomena Generation
-> See if we need to add some effects

**Comment by Slivo-fr** [comment]
I'm working on this

**Comment by Slivo-fr** [comment]
Done, need testing

**Comment by dukrat** [comment]
Tested.  The skill affects the Phenomena Generator Cycle time as desired.

**Comment by Slivo-fr** [comment]
Thanks, closing !
