### ISSUE TITLE
missile rigs CPU drawbacks

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#89]
Should affect rapid torp launchers 

See http://evehq.co/forum/viewtopic.php?f=5&t=376

**Comment by Slivo-fr** [comment]
I'll work on this

**Comment by Slivo-fr** [comment]
Done, can someone please test it ?

**Comment by dukrat** [comment]
Tested.  Rapid torp launchers are now effect by all missile rig cpu drawbacks.

**Comment by Slivo-fr** [comment]
Thanks, closing
