### ISSUE TITLE
Alpha clone API

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#91]
EveHQ doesn't seem to work with pilot in alpha clone state

See http://evehq.co/forum/viewtopic.php?f=9&t=381

**Comment by Slivo-fr** [comment]
Working on this

**Comment by Slivo-fr** [comment]
Done, need some testing !

**Comment by dukrat** [comment]
Things seem to be all in order.

**Comment by Slivo-fr** [comment]
Thanks !
