### ISSUE TITLE
Alpha clone training time

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#92]
Adjust training speed for alpha clones

**Comment by dukrat** [comment]
Okay I think I got all the places that this needed changed.  Only two, not so bad.  Will update when the character objects are recreated.  I believe this happens on QueryMyEveServer() which appears to be any of the API Update buttons.  If I'm right in that I think it should be all set.

**Comment by Slivo-fr** [comment]
Done, need testing. I'll take a look tomorrow :)

**Comment by Slivo-fr** [comment]
Tested, training time seems accurate ! Thanks :)
