### ISSUE TITLE
Fleet effect window

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#93]
Rework the window to allow multiples effects

**Comment by Slivo-fr** [comment]
After some of you suggest, we will remove the fleet effect window and use the remote effect tab to apply command burst to fitting if possible. Simpler is better :)
(for the user at least)

**Comment by PaulKPetersonCO** [comment]
I will attempt to get the command bursts working in the remote effect tab and once I have it working I will remove the fleet effect objects.

**Comment by Slivo-fr** [comment]
Removed, testing needed

**Comment by dukrat** [comment]
The Remote Effects tab Fitting and Pilot drop downs just keep redrawing for me with no content.  So I can't pick a Fitting or Pilot.

**Comment by Slivo-fr** [comment]
I believe there is something wrong with this issue, my fitting and pilot drop down are empty in the remote effect tab. I'm trying to find out why

**Comment by Slivo-fr** [comment]
Found, and fixed with d0b592e0e1bb7d6f3ca4e68840fc32a1469b59d5

**Comment by Slivo-fr** [comment]
Well, not closing as effect doesn't seems to be testable right now.

**Comment by dukrat** [comment]
Only a few of the effects seem to be working.

**Comment by Slivo-fr** [comment]
Seems good to me, tested tonight with phenomena and command bursts !
