### ISSUE TITLE
Command Ship Bonuses

### ISSUE THREAD

**Issue by dukrat** [Slivo-fr/EveHQ#97]
Believe effect needs to be added as well as assigned to ship bonuses.  
**edit slivo to clarify** : bonuses of command ships have been changed, they need to be updated.

**Comment by Slivo-fr** [comment]
I'm not sure to understand this one, can you explain it a bit more ?

**Comment by PaulKPetersonCO** [comment]
The Leadership, Wing Command and Fleet Command skills have been changed to now boost the area of effect for command bursts

**Comment by Slivo-fr** [comment]
Agree, but I still don't get the point of the issue

**Comment by dukrat** [comment]
I thought something more had to be done to start using the AOE size effect with ship bonuses, but I see that it has been used on the Orca now.  

There are a few ships that need this bonus added to their ship bonuses.

**Comment by Slivo-fr** [comment]
Well, if the skill affect the module effect size, there is no relation with the ship. It should be added in the effect CSV and be global.

**Comment by PaulKPetersonCO** [comment]
This would just be for display of the area of effect attribute for the module. it should not need to be used in any way. Correct?

**Comment by dukrat** [comment]
For example the Sleipnir has a role bonus of 100% bonus to Command Burst area of effect range

Yes I do believe the only place this would show would be on the AoE attribute of the module if you show info on it.

**Comment by Slivo-fr** [comment]
You are correct Paul
The role bonus need to be updated indeed, I didn't notice those changes.
Renaming the issue to make it more clear, and adding it to the ascension project

**Comment by dukrat** [comment]
Working on this in Effects.csv and ShipBonuses.csv.

**Comment by dukrat** [comment]
Done.  Needs testing of command dessies, command ships, bcs (except snipers but don't forget gnosis), carriers, supers, fax, titans, rorq, orca, porpoise, T3Cs, and all fleet support skills.

**Comment by Slivo-fr** [comment]
Pontifex bonus doesn't seem to affect related command bursts

**Comment by Slivo-fr** [comment]
Commands ships are fine.
Faction BCs are fine.
Standard BCs are fine.
Gnosis is fine.
Archon has 2% bonus to effect & duration instead of 1%.
Others carriers and supers carriers are fine.
Apostle has 2% bonus to effect & duration instead of 1%.
Others FAX are fine.
Titans are fine.
Rorqual is fine.
Orca is fine.
Porpoise is fine.
Fleet support skills looks fine too.

I'm unable to test T3C at the moment, subsystem does not show up. I'm opening a dedicated issue.

**Comment by Slivo-fr** [comment]
Tengu warfare processor has a skill missmatch with legion, bonus to command burst are fine.
Others T3C are fine.

**Comment by dukrat** [comment]
Fixed.  Needs pull and retest.

**Comment by Slivo-fr** [comment]
PR merged, I will retest when I got some time

**Comment by Slivo-fr** [comment]
Tested, it's fine for me !
