### ISSUE TITLE
Siege, Bastion, and Triage can't have remote effects applied

### ISSUE THREAD

**Issue by dukrat** [Slivo-fr/EveHQ#98]
Remote effects are now possible in these modes.

**Comment by dukrat** [comment]
Working in this.

**Comment by Slivo-fr** [comment]
Did you make sure remote repair, capacitor and other effect that are not allowed aren't applied ?

**Comment by dukrat** [comment]
No.  I misread something that made me think it was all allowed just impeded.  I will put the right ones back in.

**Comment by Slivo-fr** [comment]
Thanks, please do it before any other task so I don't need to revert the merge :)
